// <auto-generated />
using System;
using MeDirectMicroservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeDirectMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230407130245_TradeAndCurrency2")]
    partial class TradeAndCurrency2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeDirectMicroservice.Models.Currency", b =>
                {
                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencySymbol");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("MeDirectMicroservice.Models.ExchangeTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AmountToTrade")
                        .HasColumnType("float");

                    b.Property<string>("CurrencyFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExchangeTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TradedAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ExchangeTrades");
                });
#pragma warning restore 612, 618
        }
    }
}
